/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazons;

import amazons.controller.CLGameController;

public class App {

    public static void main(String[] args) {
        CLGameController controller = new CLGameController();
        controller.run();
    }
}
